### ISSUE TITLE
Link repo to Travic CI or an alternative

### ISSUE THREAD

**Issue by milanopatela** [nabilalamgir/soen_341#22]
find a way to link our repo to travis ci or an alternative that works with the tests. The tests don't need to be functional for now.

**Comment by milanopatela** [comment]
Still needs working. Waiting for Mustafa and Bibo to confirm. Got it working somewhat today but needs more work.

**Comment by Mouss54** [comment]
linked it with Jenkins 2.0 as well as ms build with nuget.exe.
