### ISSUE TITLE
Running the project

### ISSUE THREAD

**Issue by milanopatela** [nabilalamgir/soen_341#29]
Saad appears to be unable to run the project. Even the he added the database he seems to get the following problems:
Everyone please try to run the project at home and see if you can even run it.
If you can then help those who can't find a solution and post what you did here.

![84514308_655329791943395_6060160814130659328_n](https://user-images.githubusercontent.com/21264522/74384708-e6883580-4dbf-11ea-8644-78faf1cd14f3.jpg)

**Comment by milanopatela** [comment]
a possible solution could to delete and remake the model class

**Comment by zaad97** [comment]
When I got the problem, I was using the Concordia's Lab Computer.
When i tried to open the project at home, I was able to see the Home Page.

### even though it worked for me, PLEASE check if it works on your computer/laptop.

**Comment by milanopatela** [comment]
Alright so @zaad97 , you can do stuff right. For the time being, is it safe to assume that the problem was someone had Concordia only?

**Comment by milanopatela** [comment]
Correcting something i said before, please do not delete and remake the model class. It may cause issues.

**Comment by zaad97** [comment]
I will try to work on a Concordia computer to see if it is really only an issue that happens to Concordia's computers

**Comment by zaad97** [comment]
> Alright so @zaad97 , you can do stuff right. For the time being, is it safe to assume that the problem was someone had Concordia only?

Hard to say, because today, i was working on a computer from Concordia. I tried to make a new database in a new project and it worked. So I have a feeling that there is something in our DB that is messing up the DB connection.
**if this issue occurs in your computer/laptop, let us know immediately.**

**Comment by milanopatela** [comment]
Alright it appears to be running for most but there are little bugs but this issue can be closed.
