### ISSUE TITLE
Database Issue: The "Role" column is missing.

### ISSUE THREAD

**Issue by zaad97** [nabilalamgir/soen_341#30]
In the sign up page, there is a field box "Role". For testing purpose I wrote: "Admin".
When I clicked the ""Create" button, it instantly crashed because the Table Users does not have the column "Role".

### Solution  - Update the Database.sql file

@milanopatela , I will update the Database.sql file, however i don't know if the datatype should be _varchar(100) not null_. If it is wrong, please correct it.

For everyone else, if you already created the DB, add the following statement in a SQL Query:
ALTER TABLE [dbo].[Users]
ADD Role varchar(100) not null;

**Comment by zaad97** [comment]
The commit f0bf354 solved the issue. All it needs is to change the datatype if required.

**Comment by milanopatela** [comment]
It isn't required, but thanks for fixing that. Actually roles wont be necessary at all so it will probably be removed in the future. Thanks. You can close this when you want @zaad97
