### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by milanopatela** [nabilalamgir/soen_341#32]
@bibodanho 
@Mouss54 

Prepare theoretical unit tests for the project in considerations of what the requirements are. Do some light testing on your end. Please keep updates by commenting on this issue.

**Comment by milanopatela** [comment]
Try adding some mini test and test it.

**Comment by Mouss54** [comment]
MSBUILD failed since its only for .net core apps, will move to Build deploy and test with jenkins 2.0

**Comment by nabs1996** [comment]
unit test vs acceptance test.. clarification please @milanopatela

**Comment by milanopatela** [comment]
asking me this now?
too late project ends tonight. 
You could have email teacher even or asked me earlier
