### ISSUE TITLE
Meeting Jan23rd Documentation

### ISSUE THREAD

**Issue by milanopatela** [nabilalamgir/soen_341#4]
Sara, you said that you kept note of the meeting as well.
I uploaded mine already but I probably should have done a pull request.
For the time being could you please, check my notes and compare to yours. Comment afterwards
on this issue page on what changes would be good. Upload yours as a commit or a pull request and we can review it.

**Comment by milanopatela** [comment]
@saradohakhan  
Hey so the requirements is actually to make a wiki page for all this documentation.
I went ahead and made a page for it: https://github.com/nabilalamgir/soen_341/wiki/Meetings
This is where the meeting documentation will be placed in its final form.
Based on example provided on moodle. https://github.com/n2chao/SOEN341/wiki/MEETING-MINUTES

**Comment by ghost** [comment]
I look at it and it is all good for the meeting documentation.
