### ISSUE TITLE
Find a way to upload picture and save it to database

### ISSUE THREAD

**Issue by milanopatela** [nabilalamgir/soen_341#48]
After you find a way to upload picture: https://github.com/nabilalamgir/soen_341/issues/49 and https://github.com/nabilalamgir/soen_341/issues/50

**Comment by zaad97** [comment]
All information is in the pull request #54 . 

Make sure to merge pull request before closing this issue.

**Comment by zaad97** [comment]
Pull request Merged. Closing this issue.
