### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by milanopatela** [nabilalamgir/soen_341#76]
Make a new branch
Constantly update from master
Play around with the looks.
Avoid deleting existing css data. Comment out is better.
Comment on this issue progress often (minor and major, use judgement)

**Comment by milanopatela** [comment]
Cancelled

**Comment by milanopatela** [comment]
Reopended for now

**Comment by Mouss54** [comment]
added two images as well as an image folder. 
changed the layout page and the index page

**Comment by milanopatela** [comment]
two images isn't enough
no major visual changes were made
closing
