### ISSUE TITLE
As a user I would like to search for post by its title or user's username

### ISSUE THREAD

**Issue by zaad97** [nabilalamgir/soen_341#86]
This search bar will help the user to search another user or find a post with the word in the title.

**Comment by milanopatela** [comment]
I accidentally started that too. although its limited only to the trending pages.
I assume the search you implement will be available in all pages and link to a result page?
Also this is a user story so it needs to be more detailed.

**Comment by milanopatela** [comment]
Child: https://github.com/nabilalamgir/soen_341/issues/87

**Comment by milanopatela** [comment]
Also roles were added so model will need to be remade most likely but I already did on master. I will branch off now. @zaad97 
Add yourself as a user and change your Role to ADMIN
