### ISSUE TITLE
Add a search bar in the trending page

### ISSUE THREAD

**Issue by milanopatela** [nabilalamgir/soen_341#87]
Parent: #86

**Comment by milanopatela** [comment]
Search bar is added but additional functionality needed in the form of the drop down list.
It is supposed to help filter further by either searching through post titles or usernames or both.
@zaad97  take a look at my branch or update from my branch.
Trending4 is the latest

**Comment by milanopatela** [comment]
Complete

**Comment by zaad97** [comment]
Found a small issue. The Html.BeginForm is looking for Trending4 instead of Trending. 
I will fix it.
